"""empty message

Revision ID: 0c8eafe18ddc
Revises: 
Create Date: 2020-03-31 03:31:56.232329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8eafe18ddc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrys',
    sa.Column('_id', sa.String(length=100), nullable=False),
    sa.Column('id_patient', sa.String(length=100), nullable=True),
    sa.Column('id_hospital', sa.String(length=100), nullable=True),
    sa.Column('id_doctor', sa.String(length=100), nullable=True),
    sa.Column('patient', sa.String(length=100), nullable=True),
    sa.Column('hospital', sa.String(length=100), nullable=True),
    sa.Column('doctor', sa.String(length=100), nullable=True),
    sa.Column('medical_observations', sa.String(length=500), nullable=True),
    sa.Column('health_condition', sa.String(length=300), nullable=True),
    sa.Column('doctor_specialty', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('users',
    sa.Column('_id', sa.String(length=100), nullable=False),
    sa.Column('identification', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('type_user', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('medical_services', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('hashed_password', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_password', sa.DateTime(), nullable=True),
    sa.Column('id_hospital', sa.String(length=100), nullable=True),
    sa.Column('doctor_specialty', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('registrys')
    # ### end Alembic commands ###
