FROM python:3.7

WORKDIR /app


COPY ./ /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

WORKDIR /app
COPY ./requirements.txt /app/

ENV FLASK_APP=app.py
ENV FLASK_DEBUG=1
ENV FLASK_ENV=development

EXPOSE 8888
CMD flask run --host=0.0.0.0 --port=8888
